<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FV9RENB" ignored="0" name="Add_05" tests="1" failures="1" timestamp="12 Jun 2020 17:34:13 GMT" time="1.832" errors="0">
  <testcase name="addStaff1" time="0.168" classname="java5.assignment.test.DepartDAOTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at java5.assignment.test.DepartDAOTest.addStaff1(DepartDAOTest.java:65)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- addStaff1 -->
</testsuite> <!-- Add_05 -->
